services:
  db:
    image: postgres:18.3-alpine
    container_name: postgres-love4animals
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: love4animals
      PGDATA: /var/lib/postgresql/data/pgdata # <--- ¡ESTA ES LA LÍNEA MÁGICA!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.14.0
    container_name: pgadmin-love4animals
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  
